### ISSUE TITLE
Hopper support

### ISSUE THREAD

**Issue by luduma** [jummes/MoreCompost#11]
Could you please add the support for hoppers, so that if you place a hopper with a custom item in it, it actually composts.

**Comment by ZamponiMarco** [comment]
So you mean using the hoppers as a replacement for composters? Every hopper or only certain ones? 

Also, if you could tell me a use case to understand better this feature would help me a lot, thanks for the suggestion!

**Comment by luduma** [comment]
No I mean in vanilla minecraft, you can put a hopper on top of a composter to fill it up, and a hopper under the composter to collect the bone beal. Using an added item in the hopper doensn't work, it just stays in the hopper instead of getting in the composter.

**Comment by ZamponiMarco** [comment]
Such feature is already implemented and I just tested it in MoreComport 2.1.3 and it works.

Probably your composter isn't assigned to any player, that's why it doesn't work. To verify this you can just look at your composter and use the command /mc inspect to see if the composter has an owner.

If such composter doesn't have an owner, you can set it just by removing it and placing it again without further problems.
